function h = mkMultilineEdit(parent, pos, bg, fg)
    h = uicontrol(parent, 'Style', 'edit', 'Max', 10, 'Min', 0, ...
        'Units', 'normalized', 'Position', pos, 'HorizontalAlignment', 'left', ...
        'BackgroundColor', bg, 'ForegroundColor', fg);
end
